name: bench
run-name: "Benchmarks"

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:

  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Start RabbitMQ server
        run: ./start_rabbitmq.sh

      - name: run benchmarks
        run: ./benchmarks/run_bench.sh

      - name: run benchmarks
        run: ./benchmarks/bench_criterion.sh

  # #! issue with macos:
  # #!  - take long time to setup docker!
  # #!  - bench test take significantly much longer time!
  # macos:
  #   runs-on: macos-11

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: docker-practice/actions-setup-docker@master

  #     - name: Start RabbitMQ server
  #       run: ./start_rabbitmq.sh

  #     - name: run benchmarks
  #       run: ./benchmarks/run_bench.sh

  #     - name: run benchmarks
  #       run: ./benchmarks/run_bench.sh