name: codecov
run-name: 'Test coverage'

on: [push, workflow_dispatch]

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start RabbitMQ server
      run:  |
        sudo chown -R 1001:root rabbitmq_conf/server
        sudo chmod 755 rabbitmq_conf/server
        sudo chmod 400 rabbitmq_conf/server/*
        docker-compose up -d    
    
    - name: Cargo test instrumented
      run: LLVM_PROFILE_FILE="default_%m.profraw" RUSTFLAGS="-C instrument-coverage -C codegen-units=1" cargo test -p amqprs --all-features --tests

    - name: Merge coverage data
      run: llvm-profdata-14 merge -sparse amqprs/default_*.profraw -o amqprs.profdata

    - name: Generate coverage report
      run: |
        object_list=$(for file in $(LLVM_PROFILE_FILE="default_%m.profraw" RUSTFLAGS="-C instrument-coverage -C codegen-units=1" cargo test -p amqprs --all-features --tests --no-run --message-format=json | jq -r "select(.profile.test == true) | .filenames[]"); do printf "%s %s " --object $file; done)
        llvm-cov-14 report --use-color --ignore-filename-regex='/.cargo/registry' --ignore-filename-regex='rustc/' --ignore-filename-regex='tests/'  --instr-profile=amqprs.profdata ${object_list}

