name: integration-test

run-name: 'Run test against real rabbitmq server'

on: [push, workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:

  integration_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start RabbitMQ
      run:  |
        sudo chown -R 1001:root rabbitmq_conf/tls-test
        sudo chmod 755 rabbitmq_conf/tls-test
        sudo chmod 400 rabbitmq_conf/tls-test/*
        docker-compose up -d

    - name: Build 
      run: cargo build --all-features --verbose

    - name: Run doc tests
      run: cargo test  --all-features --doc --verbose

    - name: Run lib unit tests
      run: cargo test  --all-features --lib --verbose
    
    - name: Run integration tests
      run: cargo test  --all-features --test '*'

    - name: Run examples
      run: cargo run --example 2>&1 | grep -E '^ ' | xargs -n1 cargo run --all-features --example

    - name: default feature test
      run: cargo test

    - name: tracing feature test
      run: cargo test -F tracing

    - name: compliance_assert feature test
      run: cargo test -F compliance_assert

    - name: tls feature test
      run: cargo test -F tls      