name: integration-test

run-name: 'Run test against real rabbitmq server'

on: [push, workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:

  basic_test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Start RabbitMQ
      run:  docker-compose up -d

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run examples
      run: cargo run --example 2>&1 | grep -E '^ ' | xargs -n1 cargo run --example
